### PR TITLE
Feat(pwa): setup basic

### PR DESCRIPTION
**Pull request by AugustinMauroy**
## Description

Adding basic of PWA for etherpad

## Related Issues

No related issues

### Check List

- [X] I have formatted using `npx turbo format`
- [X] I have checked the types using `npx turbo type-check`
- [X] I have tested the build using `npx turbo build`
- [X] I have covered the code with tests if necessary

### CODE REVIEW

**Review by SamTV12345 — APPROVED** [review]
That is cool. So the schema can validate if the settings are correctly entered.

**Comment by SamTV12345** [comment]
We need to check with the settings. Can we somehow cache the object or do we really need to reread the settings over and over again?

**Comment by AugustinMauroy** [comment]
> So the schema can validate if the settings are correctly entered.

Idk if he can check if valide. But it's allow to have ied auto completion/error.

> We need to check with the settings. Can we somehow cache the object or do we really need to reread the settings over and over again?

I didn't get your message

**Comment by SamTV12345** [comment]
> > So the schema can validate if the settings are correctly entered.
> 
> Idk if he can check if valide. But it's allow to have ied auto completion/error.
> 
> > We need to check with the settings. Can we somehow cache the object or do we really need to reread the settings over and over again?
> 
> I didn't get your message

Yeah great. I meant that getMessage will always read the settings.json, parse it and the parsed settings are then added in the NextJS server component. Can we somehow cache the settings.json file in a JavaScript object that is then injected in the next app?

**Comment by AugustinMauroy** [comment]
> Yeah great. I meant that getMessage will always read the settings.json, parse it and the parsed settings are then added in the NextJS server component. Can we somehow cache the settings.json file in a JavaScript object that is then injected in the next app?

Yeah. each time you call the function `getSettings` node will read file. But keep as mind Nextjs cache page/route so `manifest.ts` output is normally cache

**Comment by SamTV12345** [comment]
> > Yeah great. I meant that getMessage will always read the settings.json, parse it and the parsed settings are then added in the NextJS server component. Can we somehow cache the settings.json file in a JavaScript object that is then injected in the next app?
> 
> Yeah. each time you call the function `getSettings` node will read file. But keep as mind Nextjs cache page/route so `manifest.ts` output is normally cache

Oh that's nice. Then there is nothing to complain about. Feel free to merge.

**Pull request merged**
