### PR TITLE
feat(desing): setup basic component

### PR DESCRIPTION
**Pull request by AugustinMauroy**
## Description

Introduce a few basic components that will be used to build more complex ones

## Validation

It's should be cool. We didn't have any design system to follow so it's up to us.

## Related Issues

No Related Issues

### Check List

- [X] I have formatted using `npx turbo format`
- [X] I have checked the types using `npx turbo type-check`
- [X] I have tested the build using `npx turbo build`

> \[!NOTE]\
> To see how it's render open you edit on this branch and execute `npm run storybook`

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
Question about the messages in the live chat, from a design point of view, what's cooler, the user's name, is it initial or is it an avatar?

**Comment by SamTV12345** [comment]
I just had a look at the storybook. First of all the components really look great and fit into the theme of Etherpad. One thing I noticed is that button solid and gradient are the same.

**Review by SamTV12345 — APPROVED** [review]

**Comment by AugustinMauroy** [comment]
> One thing I noticed is that button solid and gradient are the same.

I must have gotten confused when I coded them.

EDIT: the gradient is there, but potentially not strong enough if zoomed in to see it

**Comment by SamTV12345** [comment]
> > One thing I noticed is that button solid and gradient are the same.
> 
> I must have gotten confused when I coded them.
> 
> EDIT: the gradient is there, but potentially not strong enough if zoomed in to see it

Oh yeah. I just noticed it. It is very very subtle.

**Comment by AugustinMauroy** [comment]
> It is very very subtle.

you think it should be more pronounced ?

**Comment by SamTV12345** [comment]
> > It is very very subtle.
> 
> you think it should be more pronounced ?

yes definetely. Otherwise a user won't be able to see the difference.

**Pull request merged**
